// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBridAcCEQcvK3F2PwP8D2TzoQaRI27C30',
    appId: '1:274857953848:web:34565fce05079e135174cd',
    messagingSenderId: '274857953848',
    projectId: 'test-54bc6',
    authDomain: 'test-54bc6.firebaseapp.com',
    storageBucket: 'test-54bc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oWQ_h0hSw_1_gqGa2XwJsFaOL7M6vjk',
    appId: '1:274857953848:android:2bec612e045a99fe5174cd',
    messagingSenderId: '274857953848',
    projectId: 'test-54bc6',
    storageBucket: 'test-54bc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDZbinRhpUxbS4xzqR30sEAp7s2DNXuM',
    appId: '1:274857953848:ios:478098872d4996905174cd',
    messagingSenderId: '274857953848',
    projectId: 'test-54bc6',
    storageBucket: 'test-54bc6.appspot.com',
    iosBundleId: 'com.example.blocapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDZbinRhpUxbS4xzqR30sEAp7s2DNXuM',
    appId: '1:274857953848:ios:805ec2c36f58e1985174cd',
    messagingSenderId: '274857953848',
    projectId: 'test-54bc6',
    storageBucket: 'test-54bc6.appspot.com',
    iosBundleId: 'com.example.blocapp.RunnerTests',
  );
}
